name: kcc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - Pillow>=5.2.0
  - psutil>=5.0.0
  - python-slugify>=1.2.1
  - raven>=6.0.0
  - distro
  - pip
  - pip:
    - mozjpeg-lossless-optimization>=1.1.2
    - PyQt5>=5.6.0
