# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\MetaEditor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editorDialog(object):
    def setupUi(self, editorDialog):
        editorDialog.setObjectName("editorDialog")
        editorDialog.resize(400, 260)
        editorDialog.setMinimumSize(QtCore.QSize(400, 260))
        editorDialog.setMaximumSize(QtCore.QSize(400, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/icons/comic2ebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        editorDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(editorDialog)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editorWidget = QtWidgets.QWidget(editorDialog)
        self.editorWidget.setObjectName("editorWidget")
        self.formLayout = QtWidgets.QFormLayout(self.editorWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(self.editorWidget)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.seriesLine = QtWidgets.QLineEdit(self.editorWidget)
        self.seriesLine.setObjectName("seriesLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.seriesLine)
        self.volumeLine = QtWidgets.QLineEdit(self.editorWidget)
        self.volumeLine.setObjectName("volumeLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.volumeLine)
        self.numberLine = QtWidgets.QLineEdit(self.editorWidget)
        self.numberLine.setObjectName("numberLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numberLine)
        self.writerLine = QtWidgets.QLineEdit(self.editorWidget)
        self.writerLine.setObjectName("writerLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.writerLine)
        self.pencillerLine = QtWidgets.QLineEdit(self.editorWidget)
        self.pencillerLine.setObjectName("pencillerLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pencillerLine)
        self.inkerLine = QtWidgets.QLineEdit(self.editorWidget)
        self.inkerLine.setObjectName("inkerLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inkerLine)
        self.coloristLine = QtWidgets.QLineEdit(self.editorWidget)
        self.coloristLine.setObjectName("coloristLine")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.coloristLine)
        self.muidLine = QtWidgets.QLineEdit(self.editorWidget)
        self.muidLine.setObjectName("muidLine")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.muidLine)
        self.label_2 = QtWidgets.QLabel(self.editorWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.editorWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.editorWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.editorWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.editorWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.editorWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.editorWidget)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout.addWidget(self.editorWidget)
        self.optionWidget = QtWidgets.QWidget(editorDialog)
        self.optionWidget.setObjectName("optionWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.optionWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLabel = QtWidgets.QLabel(self.optionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.okButton = QtWidgets.QPushButton(self.optionWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Other/icons/convert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon1)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.optionWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Other/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon2)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.optionWidget)

        self.retranslateUi(editorDialog)
        QtCore.QMetaObject.connectSlotsByName(editorDialog)

    def retranslateUi(self, editorDialog):
        _translate = QtCore.QCoreApplication.translate
        editorDialog.setWindowTitle(_translate("editorDialog", "Metadata editor"))
        self.label_1.setText(_translate("editorDialog", "Series:"))
        self.label_2.setText(_translate("editorDialog", "Volume:"))
        self.label_3.setText(_translate("editorDialog", "Number:"))
        self.label_4.setText(_translate("editorDialog", "Writer:"))
        self.label_5.setText(_translate("editorDialog", "Penciller:"))
        self.label_6.setText(_translate("editorDialog", "Inker:"))
        self.label_7.setText(_translate("editorDialog", "Colorist:"))
        self.label_8.setText(_translate("editorDialog", "<html><head/><body><p><a href=\"https://github.com/ciromattia/kcc/wiki/Manga-Cover-Database-support\"><span style=\" text-decoration: underline; color:#0000ff;\">MUid:</span></a></p></body></html>"))
        self.okButton.setText(_translate("editorDialog", "Save"))
        self.cancelButton.setText(_translate("editorDialog", "Cancel"))

from . import KCC_rc
