# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KCC-OSX.ui'
#
# Created: Wed Jan 15 11:34:51 2014
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KCC(object):
    def setupUi(self, KCC):
        KCC.setObjectName("KCC")
        KCC.resize(420, 397)
        KCC.setMinimumSize(QtCore.QSize(420, 397))
        KCC.setMaximumSize(QtCore.QSize(420, 397))
        font = QtGui.QFont()
        font.setPointSize(9)
        KCC.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/icons/comic2ebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KCC.setWindowIcon(icon)
        KCC.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.Form = QtWidgets.QWidget(KCC)
        self.Form.setObjectName("Form")
        self.OptionsAdvanced = QtWidgets.QFrame(self.Form)
        self.OptionsAdvanced.setEnabled(True)
        self.OptionsAdvanced.setGeometry(QtCore.QRect(4, 253, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.OptionsAdvanced.setFont(font)
        self.OptionsAdvanced.setObjectName("OptionsAdvanced")
        self.gridLayout = QtWidgets.QGridLayout(self.OptionsAdvanced)
        self.gridLayout.setObjectName("gridLayout")
        self.ProcessingBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.ProcessingBox.setFont(font)
        self.ProcessingBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ProcessingBox.setObjectName("ProcessingBox")
        self.gridLayout.addWidget(self.ProcessingBox, 1, 0, 1, 1)
        self.UpscaleBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.UpscaleBox.setFont(font)
        self.UpscaleBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.UpscaleBox.setTristate(True)
        self.UpscaleBox.setObjectName("UpscaleBox")
        self.gridLayout.addWidget(self.UpscaleBox, 1, 1, 1, 1)
        self.WebtoonBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.WebtoonBox.setFont(font)
        self.WebtoonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.WebtoonBox.setObjectName("WebtoonBox")
        self.gridLayout.addWidget(self.WebtoonBox, 3, 1, 1, 1)
        self.NoDitheringBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.NoDitheringBox.setFont(font)
        self.NoDitheringBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.NoDitheringBox.setObjectName("NoDitheringBox")
        self.gridLayout.addWidget(self.NoDitheringBox, 3, 2, 1, 1)
        self.BorderBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.BorderBox.setFont(font)
        self.BorderBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BorderBox.setTristate(True)
        self.BorderBox.setObjectName("BorderBox")
        self.gridLayout.addWidget(self.BorderBox, 3, 0, 1, 1)
        self.NoRotateBox = QtWidgets.QCheckBox(self.OptionsAdvanced)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.NoRotateBox.setFont(font)
        self.NoRotateBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.NoRotateBox.setObjectName("NoRotateBox")
        self.gridLayout.addWidget(self.NoRotateBox, 1, 2, 1, 1)
        self.DeviceBox = QtWidgets.QComboBox(self.Form)
        self.DeviceBox.setGeometry(QtCore.QRect(8, 201, 151, 34))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.DeviceBox.setFont(font)
        self.DeviceBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DeviceBox.setObjectName("DeviceBox")
        self.FormatBox = QtWidgets.QComboBox(self.Form)
        self.FormatBox.setGeometry(QtCore.QRect(262, 201, 152, 34))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.FormatBox.setFont(font)
        self.FormatBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.FormatBox.setObjectName("FormatBox")
        self.ConvertButton = QtWidgets.QPushButton(self.Form)
        self.ConvertButton.setGeometry(QtCore.QRect(160, 200, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ConvertButton.setFont(font)
        self.ConvertButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Other/icons/convert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ConvertButton.setIcon(icon1)
        self.ConvertButton.setObjectName("ConvertButton")
        self.DirectoryButton = QtWidgets.QPushButton(self.Form)
        self.DirectoryButton.setGeometry(QtCore.QRect(5, 160, 156, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.DirectoryButton.setFont(font)
        self.DirectoryButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Other/icons/folder_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DirectoryButton.setIcon(icon2)
        self.DirectoryButton.setObjectName("DirectoryButton")
        self.FileButton = QtWidgets.QPushButton(self.Form)
        self.FileButton.setGeometry(QtCore.QRect(260, 160, 157, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.FileButton.setFont(font)
        self.FileButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Other/icons/document_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileButton.setIcon(icon3)
        self.FileButton.setObjectName("FileButton")
        self.ClearButton = QtWidgets.QPushButton(self.Form)
        self.ClearButton.setGeometry(QtCore.QRect(160, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.ClearButton.setFont(font)
        self.ClearButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Other/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearButton.setIcon(icon4)
        self.ClearButton.setObjectName("ClearButton")
        self.OptionsBasic = QtWidgets.QFrame(self.Form)
        self.OptionsBasic.setGeometry(QtCore.QRect(5, 233, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.OptionsBasic.setFont(font)
        self.OptionsBasic.setObjectName("OptionsBasic")
        self.MangaBox = QtWidgets.QCheckBox(self.OptionsBasic)
        self.MangaBox.setGeometry(QtCore.QRect(9, 10, 130, 18))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.MangaBox.setFont(font)
        self.MangaBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MangaBox.setObjectName("MangaBox")
        self.QualityBox = QtWidgets.QCheckBox(self.OptionsBasic)
        self.QualityBox.setGeometry(QtCore.QRect(282, 10, 135, 18))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.QualityBox.setFont(font)
        self.QualityBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.QualityBox.setTristate(True)
        self.QualityBox.setObjectName("QualityBox")
        self.RotateBox = QtWidgets.QCheckBox(self.OptionsBasic)
        self.RotateBox.setGeometry(QtCore.QRect(145, 10, 130, 18))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.RotateBox.setFont(font)
        self.RotateBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.RotateBox.setObjectName("RotateBox")
        self.JobList = QtWidgets.QListWidget(self.Form)
        self.JobList.setGeometry(QtCore.QRect(10, 50, 401, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.JobList.setFont(font)
        self.JobList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.JobList.setStyleSheet("QListWidget#JobList {background:#ffffff;background-image:url(:/Other/icons/list_background.png);background-position:center center;background-repeat:no-repeat;}QScrollBar:vertical{border:1px solid #999;background:#FFF;width:5px;margin:0}QScrollBar::handle:vertical{background:DarkGray;min-height:0}QScrollBar::add-line:vertical{height:0;background:DarkGray;subcontrol-position:bottom;subcontrol-origin:margin}QScrollBar::sub-line:vertical{height:0;background:DarkGray;subcontrol-position:top;subcontrol-origin:margin}QScrollBar:horizontal{border:1px solid #999;background:#FFF;height:5px;margin:0}QScrollBar::handle:horizontal{background:DarkGray;min-width:0}QScrollBar::add-line:horizontal{width:0;background:DarkGray;subcontrol-position:bottom;subcontrol-origin:margin}QScrollBar::sub-line:horizontal{width:0;background:DarkGray;subcontrol-position:top;subcontrol-origin:margin}")
        self.JobList.setProperty("showDropIndicator", False)
        self.JobList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.JobList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.JobList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.JobList.setObjectName("JobList")
        self.BasicModeButton = QtWidgets.QPushButton(self.Form)
        self.BasicModeButton.setGeometry(QtCore.QRect(5, 10, 210, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.BasicModeButton.setFont(font)
        self.BasicModeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BasicModeButton.setObjectName("BasicModeButton")
        self.AdvModeButton = QtWidgets.QPushButton(self.Form)
        self.AdvModeButton.setGeometry(QtCore.QRect(207, 10, 210, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AdvModeButton.setFont(font)
        self.AdvModeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AdvModeButton.setObjectName("AdvModeButton")
        self.OptionsAdvancedGamma = QtWidgets.QFrame(self.Form)
        self.OptionsAdvancedGamma.setEnabled(True)
        self.OptionsAdvancedGamma.setGeometry(QtCore.QRect(5, 303, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.OptionsAdvancedGamma.setFont(font)
        self.OptionsAdvancedGamma.setObjectName("OptionsAdvancedGamma")
        self.GammaLabel = QtWidgets.QLabel(self.OptionsAdvancedGamma)
        self.GammaLabel.setGeometry(QtCore.QRect(20, 0, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.GammaLabel.setFont(font)
        self.GammaLabel.setObjectName("GammaLabel")
        self.GammaSlider = QtWidgets.QSlider(self.OptionsAdvancedGamma)
        self.GammaSlider.setGeometry(QtCore.QRect(110, 10, 290, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        self.GammaSlider.setFont(font)
        self.GammaSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.GammaSlider.setMaximum(500)
        self.GammaSlider.setSingleStep(5)
        self.GammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GammaSlider.setObjectName("GammaSlider")
        self.ProgressBar = QtWidgets.QProgressBar(self.Form)
        self.ProgressBar.setGeometry(QtCore.QRect(10, 10, 401, 35))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProgressBar.setFont(font)
        self.ProgressBar.setAutoFillBackground(True)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.ProgressBar.setFormat("")
        self.ProgressBar.setObjectName("ProgressBar")
        self.OptionsExpert = QtWidgets.QFrame(self.Form)
        self.OptionsExpert.setGeometry(QtCore.QRect(5, 335, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.OptionsExpert.setFont(font)
        self.OptionsExpert.setObjectName("OptionsExpert")
        self.ColorBox = QtWidgets.QCheckBox(self.OptionsExpert)
        self.ColorBox.setGeometry(QtCore.QRect(9, 11, 130, 18))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.ColorBox.setFont(font)
        self.ColorBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ColorBox.setObjectName("ColorBox")
        self.OptionsExpertInternal = QtWidgets.QFrame(self.OptionsExpert)
        self.OptionsExpertInternal.setGeometry(QtCore.QRect(95, 0, 315, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        self.OptionsExpertInternal.setFont(font)
        self.OptionsExpertInternal.setObjectName("OptionsExpertInternal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.OptionsExpertInternal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wLabel = QtWidgets.QLabel(self.OptionsExpertInternal)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.wLabel.setFont(font)
        self.wLabel.setObjectName("wLabel")
        self.gridLayout_2.addWidget(self.wLabel, 0, 0, 1, 1)
        self.customWidth = QtWidgets.QLineEdit(self.OptionsExpertInternal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customWidth.sizePolicy().hasHeightForWidth())
        self.customWidth.setSizePolicy(sizePolicy)
        self.customWidth.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.customWidth.setFont(font)
        self.customWidth.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.customWidth.setAcceptDrops(False)
        self.customWidth.setMaxLength(4)
        self.customWidth.setObjectName("customWidth")
        self.gridLayout_2.addWidget(self.customWidth, 0, 1, 1, 1)
        self.hLabel = QtWidgets.QLabel(self.OptionsExpertInternal)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.hLabel.setFont(font)
        self.hLabel.setObjectName("hLabel")
        self.gridLayout_2.addWidget(self.hLabel, 0, 2, 1, 1)
        self.customHeight = QtWidgets.QLineEdit(self.OptionsExpertInternal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customHeight.sizePolicy().hasHeightForWidth())
        self.customHeight.setSizePolicy(sizePolicy)
        self.customHeight.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.customHeight.setFont(font)
        self.customHeight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.customHeight.setAcceptDrops(False)
        self.customHeight.setMaxLength(4)
        self.customHeight.setObjectName("customHeight")
        self.gridLayout_2.addWidget(self.customHeight, 0, 3, 1, 1)
        KCC.setCentralWidget(self.Form)
        self.statusBar = QtWidgets.QStatusBar(KCC)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(8)
        self.statusBar.setFont(font)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        KCC.setStatusBar(self.statusBar)
        self.ActionBasic = QtWidgets.QAction(KCC)
        self.ActionBasic.setCheckable(True)
        self.ActionBasic.setChecked(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ActionBasic.setFont(font)
        self.ActionBasic.setObjectName("ActionBasic")
        self.ActionAdvanced = QtWidgets.QAction(KCC)
        self.ActionAdvanced.setCheckable(True)
        self.ActionAdvanced.setObjectName("ActionAdvanced")

        self.retranslateUi(KCC)
        QtCore.QMetaObject.connectSlotsByName(KCC)
        KCC.setTabOrder(self.DirectoryButton, self.FileButton)
        KCC.setTabOrder(self.FileButton, self.ConvertButton)
        KCC.setTabOrder(self.ConvertButton, self.ClearButton)

    def retranslateUi(self, KCC):
        _translate = QtCore.QCoreApplication.translate
        KCC.setWindowTitle(_translate("KCC", "Kindle Comic Converter"))
        self.ProcessingBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Disable image optimizations.</span></p></body></html>"))
        self.ProcessingBox.setText(_translate("KCC", "No optimisation"))
        self.UpscaleBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Unchecked - Nothing<br/></span><span style=\" font-size:12pt;\">Images smaller than device resolution will not be resized.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Indeterminate - Stretching<br/></span><span style=\" font-size:12pt;\">Images smaller than device resolution will be resized. Aspect ratio will be not preserved.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Checked - Upscaling<br/></span><span style=\" font-size:12pt;\">Images smaller than device resolution will be resized. Aspect ratio will be preserved.</span></p></body></html>"))
        self.UpscaleBox.setText(_translate("KCC", "Stretch/Upscale"))
        self.WebtoonBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Enable auto-splitting of webtoons like </span><span style=\" font-size:12pt; font-style:italic;\">Tower of God</span><span style=\" font-size:12pt;\"> or </span><span style=\" font-size:12pt; font-style:italic;\">Noblesse</span><span style=\" font-size:12pt;\">.<br/>Pages with a low width, high height and vertical panel flow.</span></p></body></html>"))
        self.WebtoonBox.setText(_translate("KCC", "Webtoon mode"))
        self.NoDitheringBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Create PNG files instead JPEG.<br/>Quality increase is not noticeable on most of devices.<br/>Output files </span><span style=\" font-size:12pt; font-weight:600;\">might</span><span style=\" font-size:12pt;\"> be smaller.<br/></span><span style=\" font-size:12pt; font-weight:600;\">MOBI conversion will be much slower.</span></p></body></html>"))
        self.NoDitheringBox.setText(_translate("KCC", "PNG output"))
        self.BorderBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Unchecked - Autodetection<br/></span><span style=\" font-size:12pt;\">Color of margins fill will be detected automatically.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Indeterminate - White<br/></span><span style=\" font-size:12pt;\">Margins will be filled with white color.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Checked - Black<br/></span><span style=\" font-size:12pt;\">Margins will be filled with black color.</span></p></body></html>"))
        self.BorderBox.setText(_translate("KCC", "W/B margins"))
        self.NoRotateBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Disable splitting and rotation.</span></p></body></html>"))
        self.NoRotateBox.setText(_translate("KCC", "No split/rotate"))
        self.DeviceBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Target device.</span></p></body></html>"))
        self.FormatBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Output format.</span></p></body></html>"))
        self.ConvertButton.setText(_translate("KCC", "Convert"))
        self.DirectoryButton.setText(_translate("KCC", "Add directory"))
        self.FileButton.setText(_translate("KCC", "Add file"))
        self.ClearButton.setText(_translate("KCC", "Clear list"))
        self.MangaBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Enable right-to-left reading.</span></p></body></html>"))
        self.MangaBox.setText(_translate("KCC", "Manga mode"))
        self.QualityBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Unchecked - Normal quality mode<br/></span><span style=\" font-size:12pt; font-style:italic;\">Use it when Panel View support is not needed.</span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\"><br/></span><span style=\" font-size:12pt;\">- Maximum quality when zoom is not enabled.<br/>- Poor quality when zoom is enabled.<br/>- Lowest file size.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Indeterminate - High quality mode<br/></span><span style=\" font-size:12pt; font-style:italic;\">Not zoomed image </span><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">might </span><span style=\" font-size:12pt; font-style:italic;\">be a little blurry.<br/>Smaller images might be forcefully upscaled in this mode.</span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\"><br/></span><span style=\" font-size:12pt;\">- Medium/High quality when zoom is not enabled.<br/>- Maximum quality when zoom is enabled.</span></p><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Checked - Ultra quality mode<br/></span><span style=\" font-size:12pt; font-style:italic;\">Maximum possible quality.</span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\"><br/></span><span style=\" font-size:12pt;\">- Maximum quality when zoom is not enabled.<br/>- Maximum quality when zoom is enabled.<br/>- Very high file size.</span></p></body></html>"))
        self.QualityBox.setText(_translate("KCC", "High/Ultra quality"))
        self.RotateBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Disable splitting of two-page spreads.<br/>They will be rotated instead.</span></p></body></html>"))
        self.RotateBox.setText(_translate("KCC", "Horizontal mode"))
        self.BasicModeButton.setText(_translate("KCC", "Basic"))
        self.AdvModeButton.setText(_translate("KCC", "Advanced"))
        self.GammaLabel.setText(_translate("KCC", "Gamma: Auto"))
        self.ColorBox.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Don\'t convert images to grayscale.</span></p></body></html>"))
        self.ColorBox.setText(_translate("KCC", "Color mode"))
        self.wLabel.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Resolution of target device.</span></p></body></html>"))
        self.wLabel.setText(_translate("KCC", "Custom width: "))
        self.customWidth.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Resolution of target device.</span></p></body></html>"))
        self.customWidth.setInputMask(_translate("KCC", "0000"))
        self.hLabel.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Resolution of target device.</span></p></body></html>"))
        self.hLabel.setText(_translate("KCC", "Custom height: "))
        self.customHeight.setToolTip(_translate("KCC", "<html><head/><body><p><span style=\" font-size:12pt;\">Resolution of target device.</span></p></body></html>"))
        self.customHeight.setInputMask(_translate("KCC", "0000"))
        self.ActionBasic.setText(_translate("KCC", "Basic"))
        self.ActionAdvanced.setText(_translate("KCC", "Advanced"))

import KCC_rc
